
// EVTask.h

#ifndef __EV_TASK_H__
#define __EV_TASK_H__

#include <QRunnable>
#include <QObject>
#include <QRunnable>

// Q_OBJECT missing in the original file generated by class wizard.
// because we set this class with base class QRunnable
// with no inheritance in the class wizard
// We do not have this. So, we cannot use signal/slot
// But we need them.
// Thus, we should use multiple inheritance: QObject inserted here

class EVTask : public QObject, public QRunnable
{
  Q_OBJECT
public:
  EVTask();

signals:
  // notify to the main thread when we're done
  void Result(int Number);

protected:
  void run();
};

#endif // __EV_TASK_H__

